config/routes.rb
ListIt::Application.routes.draw do

  resources :subscriptions

  resources :user_sessions 

  match '/auth/twitter/callback' => "user_sessions#twitter_auth"  

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
  match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation

  match 'forgot_password' => 'user_sessions#forgot_password', :as => :forgot_password, :via => :get
  match 'forgot_password' => 'user_sessions#forgot_password_lookup_email', :as => :forgot_password, :via => :post

  put 'reset_password/:reset_password_code' => 'users#reset_password_submit', :as => :reset_password, :via => :put
  get 'reset_password/:reset_password_code' => 'users#reset_password', :as => :reset_password, :via => :get  

  resources :users do
    member do
      post :add_subscription
      post :remove_subscription 
    end   
    
    resources :lists, :only => [] do
      collection do
        get :peek
      end
    end
  end

  resources :projects

  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup
  resources :lists do 
    collection do
      get "all" 
      get "search"
    end  
    member do 
      get 'up_vote'
      get 'down_vote'
    end

    resources :urls do
      collection do
        get "search"
        
      end
      member do 
      post "add_comment"
      end
    end

    resources :members  do 
      member do 
        delete "reject"
        
      end     
    end
  end
 
  
  match "members/manage" => "members#manage", :via => :get, :as => "manage_members"
  match 'fetch_url_content' => 'urls#fetch_url_content'
  match 'profile' => 'users#edit_profile'
  match 'about_us' => 'pages#about_us'
  match 'contact_us' => 'pages#contact_us'
  match 'terms_of_service' => 'pages#terms_of_service'
  match '/admin' => 'admin::users#index'
  namespace :admin do 
    match '/users' => "users#index" 
    match '/users/:id' => "users#show"
    match '/users/destroy/:id' => "users#destroy",:as => :delete_user,:via => [:delete]
    match '/users/deactivate/:id' => "users#deactivate",:as => :deactivate_user
    match '/users/activate/:id' => "users#activate",:as => :activate_user
    match '/lists/:user_id' => "lists#index",:as=>:user_list
    match '/lists/destroy/:id' => "lists#destroy",:as => :destroy_list,:via => [:delete]
  end
  

  root :to => 'user_sessions#new' 

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :description, :owner_id, :title, :tag_attributes,:total_vote
  validates_presence_of :title, :description
  # belongs_to :owner,:class_name => 'User',:foreign_key => "owner_id"
  has_many :user_lists, :dependent => :destroy
  has_many :users, :through => :user_lists
  has_many :list_items, :dependent=>:destroy
  has_many :urls,:dependent => :destroy
  has_many :ratings
  has_one :tag, :as => :taggable             
  has_many :subscriptions
  has_many :subscribers, :through => :subscriptions, :source => :user
  belongs_to :creator, :class_name => 'User', :foreign_key => 'user_id'
  scope :recent, order("created_at desc")
  scope :most_voted, order("total_vote desc")      
  accepts_nested_attributes_for :tag
  paginates_per 10  
    
  searchable do
    text :title
    text :description
    text :list_tags
    text :urls do
       urls.each {|url| url.title }
    end                  
    text :url_description 
    text :url_keywords
    integer :list_item_count    
    time :created_at
    time :updated_at    
  end                    
  
  def latest_updated_time
    timestamps = [updated_at]
    list_items.each do|list_item|
      timestamps << list_item.updated_at
    end
    timestamps << tag.updated_at if tag
    timestamps.sort.reverse.first
  end

  def url_description
    self.urls.collect(&:description).join(' ').gsub(/,/, '').gsub(/\n\r/, ' ')
  end                              
  
  def url_keywords
   tags = self.urls.select {|url| url.tag if url.tag.present? }
   tags.collect{ |_tag| _tag.keywords}.join(' ').gsub(/,/, '').gsub(/\n\r/, ' ')
  end
  
  def list_tags
    self.tag.keywords.gsub(/,/, '').gsub(/\n\r/, ' ')    if self.tag
  end                       
  
  def list_item_count
    self.urls.count
  end   
  
  def get_total_upvote
    self.ratings.where(:rate=>1).count
  end

  def get_total_downvote
    self.ratings.where(:rate=>-1).count
  end

  def get_total_vote
    self.total_vote
  end
                                                 
  # Adds a user to a list as a member
  # Verifies if the person requesting this membership is the moderator. If not, sends an email to the creator of the list with the details of the user.  
  # request: User ( The person initiating the request)
  # user: User ( The person to be added to the list)
  def create_moderated_membership(user, requester)  
    status = false
    if moderator?(requester)
      create_membership(user) 
      status = true
    else                                                           
      create_membership_request(user)
      Notifier.membership_request(self.creator, user, self).deliver      
      status = false                                               
    end  
    
    status
  end
  
  def create_unmoderated_membership(user)
    create_membership(user)
    status = true
  end       
  
  def reject_membership(user)
    if self.users.include?(user)
      transaction do
        user_list = self.user_lists.where(:user_id => user.id, :state => 'requested').first
        user_list.reject!
        user_list.destroy
      end
    end
  end 
  
  def members
    self.user_lists.where(:state => "accepted").includes(:user).map(&:user)
  end 
  
  def request_pending_members(user_id)
    self.user_lists.where(:state => "requested", :user_id => user_id)
  end

  def self.get_random_lists_for_landing_page
    #get most recent list   
    if rand(2) == 0
      List.recent.limit(15)
    #get most vote list
    else
      List.most_voted.limit(15)
    end
  end
          
  def is_authorized?(user)
    moderated && (moderator?(user) || members.include?(user)) || !moderated
  end    
                       
  private            
  
  def create_membership_request(user)
    self.users.push(user) if !self.users.include?(user)
  end
                                
  def create_membership(user)
    if !self.users.include?(user) 
      transaction do
        self.users.push(user) 
        user_list = self.user_lists.where(:user_id => user.id).first
        user_list.accept!
      end                                      
    else
      user_list = self.user_lists.where(:user_id => user.id, :state => 'requested').first
      user_list.accept! if user_list.present?
    end
  end  
  
  def moderator?(user)
    self.creator == user
  end
end

app/controllers/admin/lists_controller.rb
class Admin::ListsController < Admin::AdminController
  def index
    @user = User.find(params[:user_id])
    @lists = @user.created_lists.page(params[:page])
  end
  def destroy
    @user = User.find(params[:user_id])
    @list = List.find(params[:id])
    flash[:notice]= "List is successfully deleted"
    @list.destroy
    redirect_to admin_user_list_path(@user)
    
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :set_permission_for_landing_page,:only=>[:up_vote,:down_vote]
  before_filter :set_user
  before_filter :require_user 
  
  def search   
    @page = params[:page] || 1
    @lists, @paginatable_lists = SearchDelegate.list_search(params[:search_query], @page)
    render :action => "index"
  end 

  # look at a members lists
  def peek              
    @user = User.find(params[:user_id])
    @lists = @user.lists.includes(:list_items, :users).order('created_at DESC').page(params[:page])
    @title = "#{@user.name}'s Lists"
    respond_to do |format|  
      format.html { render :action => "index"}
      format.json { render json: @lists }
    end    
  end                   
  
  def all
    @lists = List.includes(:list_items, :users, :tag).order('created_at DESC').page(params[:page])
    
    respond_to do |format|  
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end
  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists.includes(:list_items, :users, :tag).order('created_at DESC').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = current_user.lists.where(:id => params[:id]).includes(:list_items, :users).first
    respond_to do |format|
      format.html { redirect_to list_urls_url(@list)}
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new
    @tag = @list.build_tag
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
    @tag = @list.tag || @list.build_tag
  end

  # POST /lists
  # POST /lists.json
  def create         
    @list = List.new(params[:list])
    @list.users.push(current_user)
    @list.creator = current_user
    @list.moderated = true if params[:moderated].to_s == "1"

    respond_to do |format|
      if @list.save               
        @list.create_unmoderated_membership(current_user)         
        flash[:notice] = "Your List was successfully created."
        format.html { redirect_to lists_url }
        format.json { render json: @list, status: :created, location: @list }
      else
        @tag = @list.tag || @list.build_tag
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])
    @tag = @list.tag || @list.build_tag
    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
       @tag = @list.tag || @list.build_tag
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])     
    respond_to do |format|
      if (@list.creator == current_user || current_user.is_admin?) && @list.users.size == 1       
        flash[:notice] = "Your list has been successfully removed."
        @list.destroy     
          format.html { redirect_to lists_url }
          format.json { head :no_content }
      else
         flash[:notice] = "This list cannot be deleted. There are other members who are part of this list."
         format.html { redirect_to lists_url }
         format.json { head :no_content }
      end
    end
  end
  def up_vote
    rating = Rating.up_vote(params[:id],@user.id)
    render json:{"error"=>rating[1],"vote"=>rating[2]}.to_json
 
  end
  def down_vote
    rating=Rating.down_vote(params[:id],@user.id)
    render json:{"error"=>rating[1],"vote"=>rating[2]}.to_json
  end
  
  private

  def set_user
    @user = current_user
  end
  
end

app/helpers/lists_helper.rb
module ListsHelper
  def up_vote_text(list)
    "Up vote(#{list.get_total_upvote})"
  end
  
  def down_vote_text(list)
    "Down vote(#{list.get_total_downvote})"
  end
end

app/views/lists/_action_items.html.erb
<ul class='nav nav-pills nav-stacked'>
  <% if !@list.users.include?(current_user) %>
      <%= link_to  "Join List", list_members_url(@list, :id => current_user), :method => :post , :class => 'btn btn-primary btn-large', :style=>'width:90%;' %>
  <% else %>
     <%= link_to  "Quit List #{action_status(@list)}", list_member_url(@list, current_user), :method => :delete, :class => 'btn btn-primary btn-large', :style=> 'width:90%;' %>
  <% end %>
</ul>

app/views/lists/_form.html.erb
<%= form_for(@list,:html=>{:class=>"form-horizontal"}) do |f| %>
  <fieldset>
    <legend><%= @list.new_record? ? "New List" : "Edit List" %></legend>

    <div class="control-group <%= has_error?(@list, :title) %>">
       <label class="control-label">Title*<label/>
        <div class="controls">          
          <%= f.text_field :title,:class=>'span5' %>           
          <%= render :partial => 'shared/inline_error_message', :locals => {:object => @list, :attribute => :title }%>
        </div>  
      </div>

      <div class="control-group <%= has_error?(@list, :description) %>">
        <%= f.label :description,:class=>"control-label" %> 
        <div class="controls">
          <%= f.text_area :description ,:rows=>5,:class=>'span5'%>
          <%= render :partial => 'shared/inline_error_message', :locals => {:object => @list, :attribute => :title }%>
        </div>  
      </div>
      
      <div class="control-group <%= has_error?(@list, :tag) %>">
        <%= f.fields_for :tag do |tag_form| %>
        <%= tag_form.label "Tag",:class=>"control-label" %> 
        <div class="controls">
          <%= tag_form.text_area :keywords ,:rows=>5,:class=>'span5'%>
        </div> 
        <% end%> 
      </div>
      
      <div class="control-group">
        <%= f.label :moderated, :class=>"control-label" %> 
        <div class="controls">
          <%= check_box_tag :moderated %>
        </div>  
      </div>  
      
      
      <div class="form-actions">
        <%= f.submit "Save Changes",:class=>"btn btn-primary"%>
        <%= link_to("Cancel", lists_path,:class=>'btn black-link') %>
      </div>
   </fieldset> 
<% end %>

app/views/lists/_list.html.erb
<tbody>
  <tr>
    <td class='span9'>
      <h3><%= link_to "#{list.title} (#{list.list_items.size})", list_urls_url(list) %></h3>
      <p><em><%= truncate(list.description, :length => 200, :omission => '...') %></em></p> 
      <p>
        <%= render :partial => "shared/updated_info", :locals => { :latest_updated_time => list.latest_updated_time } %>
      </p>
    </td>
    <td class='span1'>    
      <p>
      <% if !list.moderated? && list.users.include?(current_user) %>
        <%= link_to 'Edit', edit_list_path(list) %> 
      <% end %>
      </p>
      <p>
      <%= link_to "Members(#{list.users.size}) ", list_members_path(list) %> 
      </p>
      <p id="list_<%= list.id %>" class="sbscr_actions">
      <%= subscribe_actions(list) %>
      </p>
      <p>
      <% if list.creator == current_user %>
        <%= link_to "Destroy", list_path(list), :method => :delete %>
      <% end %>
      </p>         
    </td>
    <td class="span1 <%= dom_id(list) %>">
      <!-- <p id="<%#= dom_id(list)%>">             -->
      <p><%= link_to image_tag('glyphicons_213_up_arrow.png'), up_vote_list_path(list),:class=>'up_vote' ,"data-list_id"=> list.id%> </p>
      <p><span id='vote_value' data-list_id="<%= list.id %>"><%= list.get_total_vote%></span></p>
      <p><%= link_to image_tag('glyphicons_212_down_arrow.png'), down_vote_list_path(list),:class=>'down_vote',"data-list_id"=> list.id %></p>
      <!-- </p>                                             -->
      <span class="vote_error"></span>
      </p>   
    </td>
    <td class='span1'>
      <p>
      <%= sharethis(list) %> 
      </p>      
    </td>
  </tr>
</tbody>

app/views/lists/_lists.html.erb
<table class="table table-striped">
  <thead>
  </thead>                                            

 <%= render :partial => 'lists/list', :collection => @lists %>

</table>                                               
<div class="user-actions">
  <div class="pull-left">
    <% if current_user.present? %>
    <a class='btn btn-primary btn-medium custom-visted' href="<%= new_list_path %>"> Create A New List </a>
    <% end %>
  </div>
  <div class='pull-right margin-top-m18'>   
    <% if current_user %>
      <% if defined?(@paginatable_lists)%>
          <%= paginate @paginatable_lists.results %>
        <% else %>
          <%= paginate @lists %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/lists/_members.html.erb
<ul class='nav nav-pills nav-stacked'>
  <li class='nav-header'>
    <%= "Members" %>
  </li>                           
  <li><%= link_to  "#{@list.creator.name} (Creator)", list_member_path(:list_id => @list.id, :id => @list.creator.id) %> </li>    
  <li><%= link_to "Members(#{@list.users.count - 1})", list_members_url(@list)%>
  <% (@list.users - [@list.creator]).each do |user| %>
    <li><%= link_to  user.name, list_member_path(:list_id => @list, :id => user.id) %> </li>
  <% end%>
</ul>

app/views/lists/all.html.erb
<% content_for :page_info do %>
  - All Lists
<% end %>

<%= render :partial => 'shared/stacked_navigation_sidebar'%>

<div class='page-header'>
  <div class='pull-right'>
    <a class='btn btn-primary btn-medium custom-visted' href="<%= new_list_path %>"> Create A New List </a>
   </div>
  <h2> Lists </h2> 
  <%= render :partial => 'shared/list_search' %>
</div>          

<%= render :partial => "lists" %>     

<% content_for :head do  %>
  <script type='text/javascript' src='http://w.sharethis.com/button/buttons.js'>
  <script type='text/javascript'>
      stLight.options({
        publisher:'<%= SHARETHIS_KEY %>',
      });
  </script>
<% end  %>

app/views/lists/edit.html.erb
<% content_for :page_info do %>
 - Edit List
<% end %>

<% content_for :sidebar do%>
  <%= render :partial => 'urls/stacked_navigation' %>
<% end %>

<%= render 'form' %>

app/views/lists/index.html.erb
<% content_for :page_info do %>
 - <%= (action_name == "index") ? "My Lists" : (action_name == "peek") ? "Member Lists" : "" %>
<% end %>

<%= render :partial => "shared/stacked_navigation_sidebar"%>

<div class='page-header'>
  <div class='pull-right'>
    <a class='btn btn-primary btn-medium custom-visted' href="<%= new_list_path %>"> Create A New List </a>
  </div>       
  <% if defined?(@title)%>
    <h2><%= @title %></h2>
  <% else %>
    <h2> My Lists </h2>   
  <% end %>
  <%= render :partial => 'shared/list_search' %>

</div>               

<%= render :partial => "lists" %>     

<% content_for :head do  %>
  <script type='text/javascript' src='http://w.sharethis.com/button/buttons.js'>
  <script type='text/javascript'>
      stLight.options({
        publisher:'<%= SHARETHIS_KEY %>',
      });
  </script>
<% end  %>

app/views/lists/new.html.erb
<% content_for :page_info do %>
 - New List
<% end %>

<% content_for :sidebar do%>
  <%= render :partial => 'urls/stacked_navigation' %>
<% end %>

<%= render 'form' %>

app/views/lists/show.html.erb
<%= content_for :sidebar do %>
  <ul class="nav nav-list">
    <li class="nav-header">Sidebar</li>
    <li class="active"> <%= link_to "Url",list_urls_path(@list)%></a></li>
  </ul> 
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @list.title %>
</p>

<p>
  <b>Owner:</b>
  <%= @list.owner_id %>
</p>

<p>
  <b>Description:</b>
  <%= @list.description %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>