config/routes.rb
ListIt::Application.routes.draw do

  resources :subscriptions

  resources :user_sessions 

  match '/auth/twitter/callback' => "user_sessions#twitter_auth"  

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
  match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation

  match 'forgot_password' => 'user_sessions#forgot_password', :as => :forgot_password, :via => :get
  match 'forgot_password' => 'user_sessions#forgot_password_lookup_email', :as => :forgot_password, :via => :post

  put 'reset_password/:reset_password_code' => 'users#reset_password_submit', :as => :reset_password, :via => :put
  get 'reset_password/:reset_password_code' => 'users#reset_password', :as => :reset_password, :via => :get  

  resources :users do
    member do
      post :add_subscription
      post :remove_subscription 
    end   
    
    resources :lists, :only => [] do
      collection do
        get :peek
      end
    end
  end

  resources :projects

  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup
  resources :lists do 
    collection do
      get "all" 
      get "search"
    end  
    member do 
      get 'up_vote'
      get 'down_vote'
    end

    resources :urls do
      collection do
        get "search"
        
      end
      member do 
      post "add_comment"
      end
    end

    resources :members  do 
      member do 
        delete "reject"
        
      end     
    end
  end
 
  
  match "members/manage" => "members#manage", :via => :get, :as => "manage_members"
  match 'fetch_url_content' => 'urls#fetch_url_content'
  match 'profile' => 'users#edit_profile'
  match 'about_us' => 'pages#about_us'
  match 'contact_us' => 'pages#contact_us'
  match 'terms_of_service' => 'pages#terms_of_service'
  match '/admin' => 'admin::users#index'
  namespace :admin do 
    match '/users' => "users#index" 
    match '/users/:id' => "users#show"
    match '/users/destroy/:id' => "users#destroy",:as => :delete_user,:via => [:delete]
    match '/users/deactivate/:id' => "users#deactivate",:as => :deactivate_user
    match '/users/activate/:id' => "users#activate",:as => :activate_user
    match '/lists/:user_id' => "lists#index",:as=>:user_list
    match '/lists/destroy/:id' => "lists#destroy",:as => :destroy_list,:via => [:delete]
  end
  

  root :to => 'user_sessions#new' 

end

app/models/url.rb
class Url < ListItem  
  attr_protected :user_id         
  validates_format_of :url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
  paginates_per 10                
  has_many :comments, :as => :commentable
  def keywords
    self.tag.keywords.gsub(/,/, '').gsub(/\n\r/, '').to_s  if self.tag.present? && self.tag.keywords.present?
  end       
  
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # GET /list_items
  # GET /list_items.json
  before_filter :set_permission_for_landing_page,:only=>[:index]
  before_filter :require_user
  before_filter :load_list, :except=>[:fetch_url_content] 
  before_filter :authorized_to_create?, :only => [:new, :create]

  def search                                                   
    @page = params[:page] || 1
    @urls, @paginatable_urls = SearchDelegate.url_search(params[:search_query],  @page, @list.id)
    render :action => "index"
  end

  def index                          
    page = params[:page] || 1
    @urls = @list.urls.page(page)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @urls }
    end
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
    @url = @list.urls.find(params[:id])
    @comments = @url.comments.includes(:user)
    @comment = @url.comments.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @url }
    end
  end

  # GET /list_items/new
  # GET /list_items/new.json
  def new
    @url = @list.urls.new
    @tag = @url.tag || @url.build_tag
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @url }
    end
  end

  # GET /list_items/1/edit
  def edit
    @url = @list.urls.find(params[:id])
    @tag = @url.tag || @url.build_tag
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @url = @list.urls.new(params[:url]) 
    @url.creator = current_user
    
    respond_to do |format|
      if @url.save        
        @list.solr_index!
        format.html { redirect_to list_urls_url(@list), notice: 'List item was successfully created.' }
        format.json { render json: @url, status: :created, location: @url }
      else
        @tag = @url.tag || @url.build_tag
        format.html { render action: "new" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /list_items/1
  # PUT /list_items/1.json
  def update                      
    @url = @list.urls.find(params[:id])
    @tag = @url.tag || @url.build_tag
    respond_to do |format|
      if @url.update_attributes(params[:url])        
        @list.solr_index!
        format.html { redirect_to list_urls_url(@list), notice: 'List item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @url = @list.urls.find(params[:id])
    respond_to do |format|
      if @url.destroy
        @list.solr_index!
        format.html { redirect_to list_urls_url }
        format.json { head :no_content }
      else
        format.html { redirect_to :back }
        format.json {render json: @url.errors, status: :unprocessable_entity}
      end
    end
  end

  def fetch_url_content
    @url = UrlData.new(params[:url])
    render json:@url.to_json
  end
  def add_comment
  
    @url = @list.urls.find(params[:id])
    @comment = @url.comments.new(:body=>params["body"],:user_id=>current_user.id)
    if @comment.save  
      flash[:notice] = "Comment successfully created"
    else 
      flash[:notice] = "Comment is not created"
    end
    redirect_to list_url_path(@list,@url)
    
  end
  protected
  def load_list
    @list = List.find(params[:list_id])
  end
  
  private
  
  def authorized_to_create?
    unless @list.is_authorized?(current_user)
      flash[:notice] = "You cannot add to this list. This is a moderated list and requires approval by the creator of the list"
      redirect_to list_urls_url(@list)
    end
  end
end

app/helpers/urls_helper.rb
module UrlsHelper

  def preview_image_for(url)
    image_url = ""
    if url.image_url.present?
      image_url = url.image_url
    else
      image_url = "/assets/no_image.png"
    end
    image_tag image_url, :size => '115x115'
  end
end

app/views/urls/_form.html.erb
<%= form_for([@list,@url],:html=>{:class=>"form-horizontal new_url"}) do |f| %>

<fieldset>   
  <legend><%= @url.new_record? ? "New Url" : "Edit Url" %></legend>
  <%= f.hidden_field :image_url %>

  <div class="control-group <%= has_error?(@url, :url) %>">
    <%= f.label "url*",:class=>"control-label" %> 
    <div class="controls">
      <%= f.text_field :url ,:rows=>5,:class=>'span5'%> &nbsp; <%= image_tag('ajax-loader.gif', :class => 'loader hidden')%>
      <%= render :partial => 'shared/inline_error_message', :locals => {:object => @url, :attribute => :url }%>
    </div>  
  </div>
  <div class="control-group <%= has_error?(@url, :title) %>">
    <%= f.label "title*" ,:class=>"control-label"%>
    <div class="controls">
      <%= f.text_field :title,:class=>'span5' %>
      <%= render :partial => 'shared/inline_error_message', :locals => {:object => @url, :attribute => :title }%>
    </div>  
  </div>

  <div class="control-group <%= has_error?(@url, :description) %>">
    <%= f.label :description,:class=>"control-label" %> 
    <div class="controls">
      <%= f.text_area :description ,:rows=>5,:class=>'span5'%>
      <%= render :partial => 'shared/inline_error_message', :locals => {:object => @url, :attribute => :description }%>
    </div>  
  </div>
  <div class="control-group">
    <%= f.fields_for :tag do |tag_form| %>
    <%= tag_form.label "Tag",:class=>"control-label" %> 
    <div class="controls">
      <%= tag_form.text_area :keywords ,:rows=>5,:class=>'span5'%>
      <%= render :partial => 'shared/inline_error_message', :locals => {:object => @url, :attribute => :keywords }%>
    </div>  
  </div>                          
  <% end %>

  <div class="form-actions">
    <%= f.submit "Save Changes",:class=>"btn btn-primary"%>
    <%=link_to("Cancel", list_urls_path(@list),:class=>'btn black-link') %>
  </div>
</fieldset> 

<% end %>

app/views/urls/_stacked_navigation.html.erb
<ul class='nav nav-pills nav-stacked'>   
  <li class='nav-header'> Views </li>
  <li class='<%= is_active?(:lists, :index) %>'>
    <%= link_to "My Lists", lists_url %>
  </li>   
  <li class='<%= is_active?(:lists, :all) %>'>
    <%= link_to "All Lists", all_lists_url %>
  </li>
</ul>

app/views/urls/edit.html.erb
<% content_for :page_info do %>
  - Edit URL
<% end %>

<% content_for :sidebar do%>
  <%= render :partial => 'urls/stacked_navigation' %>
<% end %>

<%= render 'form' %>

app/views/urls/index.html.erb
<% content_for :page_info do %>
 - List Details
<% end %>

<% content_for :sidebar do%>
<%= render :partial => "lists/action_items" %>
<%= render :partial => 'lists/members' %>
<%= render :partial => 'urls/stacked_navigation' %>
<% end %>

<div class='page-header'>
  <div class='pull-right'> 
    <% if current_user.present? && @list.members.include?(current_user) %>
      <a href="<%= new_list_url_path %>" class='btn btn-primary btn-medium'>New URL </a>
    <% end %>
  </div>
  <h2> <%= @list.title %> </h2>   
  <%= render :partial => 'shared/url_search' %>
</div>

<table class="table table-striped">
  <thead>
  </thead>
  <% @urls.each do |url| %>
  <tbody>
    <tr>
      <td>  
        <%= preview_image_for(url) %>
      </td>
      <td>
        <h3>
          <%=link_to url.title, url.url, :target => '_blank', :rel => 'no-follow' %>
        </h3>
        <p>   
          <%= link_to url.url, url.url %>
        </p>
        <p>   
          <em><%= url.description %></em>
        </p>
        <p>
          <% if url.creator.present? %>
            <%= link_to "#{url.creator.name}", list_member_url(url.list, url.creator.id)%> 
          <% end %>
          | 
          <%= render :partial => "shared/updated_info", :locals => { :latest_updated_time => url.updated_at } %>          
        </p>
        <p>
          <% if current_user == url.creator %>
            <%= link_to 'Edit', edit_list_url_path(@list,url) %> |
            <%= link_to 'Destroy', list_url_path(@list,url), confirm: 'Are you sure?', method: :delete %>                     
          <% end %>
        </p>  
      </td>
      <td>
        <%= link_to image_tag('glyphicons_309_comments.png'),list_url_path(@list,url) %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

<div class="user-actions">
  <div class="pull-left">
    <% if current_user.present? && @list.is_authorized?(current_user) %>
      <a href="<%= new_list_url_path %>" class='btn btn-primary btn-medium'>New URL </a>
    <% end %>
  </div>
  <div class='pull-right margin-top-m18'>   
    <% if defined?(@paginatable_urlss)%>
      <%= paginate @paginatable_urlss.results %>
    <% else %>
      <%= paginate @urls %>
    <% end %>
  </div>
</div>


<br />

app/views/urls/new.html.erb
<% content_for :page_info do %>
 - New URL
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'urls/stacked_navigation' %>
<% end %>

<%= render 'form' %>

app/views/urls/show.html.erb
<%= render :partial => "shared/stacked_navigation_sidebar"%>
<table class="table table-striped">
  <thead>
  </thead>
 <tbody>
    <tr>
      <td>  
        <%= preview_image_for(@url) %>
      </td>
      <td>
        <h3>
          <%=link_to @url.title, @url.url, :target => '_blank', :rel => 'no-follow' %>
        </h3>
        <p>   
          <%= link_to @url.url, @url.url %>
        </p>
        <p>   
          <em><%= @url.description %></em>
        </p>
        <p>
          <% if @url.creator.present? %>
            <%= link_to "#{@url.creator.name}", list_member_url(@url.list, @url.creator.id)%> 
          <% end %>
          | 
          <%= render :partial => "shared/updated_info", :locals => { :latest_updated_time => @url.updated_at } %>          
        </p>
        <p>
          <% if current_user == @url.creator %>
            <%= link_to 'Edit', edit_list_url_path(@list,@url) %> |
            <%= link_to 'Destroy', list_url_path(@list,@url), confirm: 'Are you sure?', method: :delete %>                     
          <% end %>
        </p>  
      </td>
     
    </tr>
  </tbody>
</table>
 <%= form_tag(add_comment_list_url_path(@list,@url),:class=>"well") do%>
  <label>Comment</label>
  <p>
  <%= text_area_tag "body","",:class=>"span6",:rows=>5,:placehoder=>"Comment goes here ....." %>
  </p>
  <%= submit_tag "Add Comment",:class=>"btn" %>
 <% end %>
<table class="table table-striped">
<thead>
</thead>
<tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td>
      <p>
        <em><%= comment.body %></em>
        <p>
         <%= link_to "#{comment.name}", list_member_url(@url.list, comment.user.id)%> |
        <span class='updated-info'>
          Created at <span class='bold-text'><%= time_ago_in_words(comment.created_at, true) %></span> ago
        </span>
      </p>  
      </td>
    </tr>
  <% end%>
  
</tbody>
</table>