config/routes.rb
ListIt::Application.routes.draw do

  resources :subscriptions

  resources :user_sessions 

  match '/auth/twitter/callback' => "user_sessions#twitter_auth"  

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
  match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation

  match 'forgot_password' => 'user_sessions#forgot_password', :as => :forgot_password, :via => :get
  match 'forgot_password' => 'user_sessions#forgot_password_lookup_email', :as => :forgot_password, :via => :post

  put 'reset_password/:reset_password_code' => 'users#reset_password_submit', :as => :reset_password, :via => :put
  get 'reset_password/:reset_password_code' => 'users#reset_password', :as => :reset_password, :via => :get  

  resources :users do
    member do
      post :add_subscription
      post :remove_subscription 
    end   
    
    resources :lists, :only => [] do
      collection do
        get :peek
      end
    end
  end

  resources :projects

  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup
  resources :lists do 
    collection do
      get "all" 
      get "search"
    end  
    member do 
      get 'up_vote'
      get 'down_vote'
    end

    resources :urls do
      collection do
        get "search"
        
      end
      member do 
      post "add_comment"
      end
    end

    resources :members  do 
      member do 
        delete "reject"
        
      end     
    end
  end
 
  
  match "members/manage" => "members#manage", :via => :get, :as => "manage_members"
  match 'fetch_url_content' => 'urls#fetch_url_content'
  match 'profile' => 'users#edit_profile'
  match 'about_us' => 'pages#about_us'
  match 'contact_us' => 'pages#contact_us'
  match 'terms_of_service' => 'pages#terms_of_service'
  match '/admin' => 'admin::users#index'
  namespace :admin do 
    match '/users' => "users#index" 
    match '/users/:id' => "users#show"
    match '/users/destroy/:id' => "users#destroy",:as => :delete_user,:via => [:delete]
    match '/users/deactivate/:id' => "users#deactivate",:as => :deactivate_user
    match '/users/activate/:id' => "users#activate",:as => :activate_user
    match '/lists/:user_id' => "lists#index",:as=>:user_list
    match '/lists/destroy/:id' => "lists#destroy",:as => :destroy_list,:via => [:delete]
  end
  

  root :to => 'user_sessions#new' 

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
  end # block optional   

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => '/assets/default_user.png'
                 
  has_many :user_lists,  :dependent => :destroy
  has_many :created_lists, :class_name => 'List', :foreign_key => 'user_id'
  has_many :lists, :through => :user_lists
  has_many :list_items
  has_many :subscriptions
  has_many :ratings 
  has_many :comments 
  has_many :projects, dependent: :destroy

  attr_accessible :name, :email, :password, :password_confirmation, :active, :description, :avatar, :twitter_id, :twitter_screenname, :twitter_avatar
  before_avatar_post_process :process_only_images

  validates_uniqueness_of :twitter_id, :if => Proc.new{|user| user.twitter_id.present?}

  validates_attachment_content_type :avatar, 
                        :message => 'Please upload correct format image',
                        :content_type => %w( image/jpeg image/png image/gif image/pjpeg image/x-png ),
                        :unless => Proc.new{|user|user.avatar.url.include?("missing.png")}
  paginates_per 25

  def active?
    active
  end

  def subscribed?(list)
    subscription = Subscription.where(:user_id => self.id, :list_id => list.id).first
    !subscription.nil?
  end

  def add_subscription_for(list)
    subscription = subscriptions.new(:list_id => list.id, :user_id => self.id)
    subscription.save
  end

  def remove_subscription_for(list)
    subscription = subscriptions.where(:list_id => list.id, :user_id => self.id).first
    subscription.destroy
  end

  def send_forgot_password!
    deactivate!
    reset_perishable_token!
    Notifier.forgot_password(self).deliver
  end

  def activate!
    self.active = true
    save
  end

  def deactivate!
    self.active = false
    save
  end

  def send_activation_instructions!
    reset_perishable_token!
    Notifier.activation_instructions(self).deliver
  end

  def send_activation_confirmation!
    reset_perishable_token!
    Notifier.activation_confirmation(self).deliver
  end

  def email_address_with_name
    "#{self.name} <#{self.email}>"
  end

  def is_admin?
    admin
  end

  # link existing users account with twitter
  def link_account(auth_hash)
    if auth_hash.present?
      parameters = {:user => {}}
      parameters[:user][:twitter_id] = auth_hash.uid
      parameters[:user][:twitter_screenname] = auth_hash.info.nickname
      parameters[:user][:twitter_avatar] = auth_hash.info.image if auth_hash.info.image.present?
      status = self.update_attributes(parameters[:user])
    else
      status = false
    end

    status
  end

  # creates a non-existing user using Twitter information
  def self.create_new_twitter_user(auth_hash)
    user = User.new(name: auth_hash.info.name, 
      twitter_id: auth_hash.uid, 
      twitter_screenname: auth_hash.info.nickname)
    user.twitter_avatar = auth_hash.info.image if auth_hash.info.image.present?
    user.generate_password
    user.generate_single_access_token
    if user.valid_twitter_user?
      status = user.save(:validate => false)
    else
      status = false
    end
    [status, user]
  end

  def valid_twitter_user?
    status = true
    user = User.where(:twitter_id => self.twitter_id).first
    if user.present?
      status = false
      user.errors.add(:twitter_id, "Must be unique")
    end

    status  
  end

  def generate_password    
    self.password = self.password_confirmation = random_string(8)
  end 


  def generate_single_access_token
    self.single_access_token = random_string(16)
  end

  private  

  def random_string(size)
    random_string = SecureRandom.hex(size)
  end
  
  def process_only_images
    if !(avatar.content_type =~ %r{^(image|(x-)?application)/(x-png|pjpeg|jpeg|jpg|png|gif)$})
      return false
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
   @users = User.order(:name).page(params[:page],:per_page => 25 )
  end
  def show
   @user = User.find(params[:id])
  end
  
   def destroy
    @user = User.find(params[:id])

    if @admin_user != @user
      @user.destroy
      flash[:notice] ="User is successfully deactivated"
    else
      flash[:notice] ="User can't deactivated"  
    end
    
    redirect_to admin_users_path
  end
  def deactivate
    @user = User.find(params[:id])

    if @admin_user != @user
      @user.deactivate!
      flash[:notice] ="User is successfully deactivated"
    else
      flash[:notice] ="User can't deactivated"  
    end
    
    redirect_to admin_users_path
  end
  def activate
    @user = User.find(params[:id])
    @user.activate!
    flash[:notice] ="User is successfully activated"
    redirect_to admin_users_path
  end
  def destroy
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "welcome", :only => :new
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update, :add_subscription, :remove_subscription]

  def new
    @user = User.new
    @lists = List.get_random_lists_for_landing_page
  end

  def create
    @user = User.new(params[:user])

    # Saving without session maintenance to skip
    # auto-login which can't happen here because
    # the User has not yet been activated
    if @user.save_without_session_maintenance
      @user.send_activation_instructions!      # new method in the User model
      flash[:notice] = "Your account has been created. Please check your e-mail for your account activation instructions!"
      redirect_to root_url
    else
      flash[:error] = @user.errors.full_messages
      render :action => :new, :layout => "welcome"
    end
  end

  def activate
    @user = User.find_using_perishable_token(params[:activation_code], 1.week) || (raise Exception)

    raise Exception if @user.active?
    if @user.activate!
      UserSession.create(@user, false)
      @user.send_activation_confirmation!
      redirect_to account_url
    else
      render :action => :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit_profile
    end
  end

  def reset_password
    @user = User.find_using_perishable_token(params[:reset_password_code], 1.week) || (raise Exception)
  end

  def reset_password_submit
    @user = User.find_using_perishable_token(params[:reset_password_code], 1.week) || (raise Exception)
    @user.active = true
    if @user.update_attributes(params[:user].merge({:active => true}))
      flash[:notice] = "Successfully reset password."
      redirect_to @user
    else
      flash[:notice] = "There was a problem resetting your password."
      render :action => :reset_password
    end
  end

  def edit_profile
    @user = current_user
  end

  def add_subscription
   @list = List.find(params[:list_id])
   @is_added = current_user.add_subscription_for(@list)
   respond_to do |format|
     format.html
     format.js
   end
  end

  def remove_subscription
   @list = List.find(params[:list_id])
   @is_removed = current_user.remove_subscription_for(@list)

   respond_to do |format|
     format.html
     format.js
   end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%#= render "shared/error_messages", :target => @user %>
<% if flash[:error].present? %>
	<div class='alert alert-error'>
		<% flash[:error].each do|error| %>
		  <li><%= error %></li>
		<% end %>
	</div>
<% end %>

<p>
  <label class="control-label">Name</label>
<div class="controls">
  <%= form.text_field :name, :class => 'span3'%>
</div>
</p>
<p>
  <label class="control-label">Email</label>
<div class="controls">
  <%= form.text_field :email, :class => 'span3'%>
</div>
</p>
<p>
  <label class="control-label"><%= form.object.new_record? ? "Password" : "Change password"  %></label>
<div class="controls">
  <%= form.password_field :password, :class => 'span3' %>
</div>
</p>
<p>
  <label class="control-label">Password confirmation</label>
<div class="controls">
  <%= form.password_field :password_confirmation, :class => 'span3' %>
</div>
</p>

app/views/users/_user_details.html.erb
<div class='row'>
  <div class="span1 thumbnail">
    <% user_img = user.avatar.url.include?("missing.png") ? "/assets/default_user.png" : user.avatar.url(:thumb) %>
    <%=h image_tag user_img %>
  </div>

    <div class="span4">
      <div class='control-group'>        
        <b>Name:</b>
        <%=h user.name %>
      </div>

      <div class='control-group'>
        <b>Description:</b>
        <%=h user.description %>
      </div>

      <% if user.twitter_id.present? %>
        <div class='control-group'>
          <b> Twitter Screen Name </b>
          <%= h user.twitter_screenname %>
        </div>
      <% end %>

      <div class='control-group'>
        <b>Last login at:</b>
        <%= h user.last_login_at %>
      </div>

      <% if user == current_user %>
        <div class='form-actions'>
          <%= link_to 'Edit', profile_path, :class => 'btn btn-primary' %>
          <% unless user.twitter_id.present? %>
            <%= link_to "Link Your Twitter Account", "/auth/twitter", :class => "btn btn-primary" %>
          <% else %>
            <%= link_to "Update Your Twitter Account", "/auth/twitter", :class => "btn btn-primary" %>
          <% end %>
        </p>
      <% end %>  
  </div>
</div>

app/views/users/add_subscription.js.erb
<% if @is_added %>
    $("#list_<%= @list.id %>.sbscr_actions").html("<%= escape_javascript subscribe_actions(@list) %> ");
<% end %>

app/views/users/edit.html.erb
h1>Edit My Account</h1>

<% form_for @user, :url => account_path do |f| %>
  <%= render :partial => "form", :object => f, :locals => { :user => @user } %>
  <%= f.submit "Update" %>
<% end %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/edit_profile.erb
<% content_for :sidebar do%>
  <%= render :partial => 'urls/stacked_navigation' %>
<% end %>

<%= form_for(@user,:html=>{:class=>"form-horizontal"}) do |f| %>
  <fieldset>
    <legend>Edit Profile</legend>


		<div class="control-group <%= has_error?(@user, :description) %>">
		  <%= f.label :description,:class=>"control-label" %> 
		  <div class="controls">
		    <%= f.text_area :description ,:rows=>5,:class=>'span5'%>
		    <%= render :partial => 'shared/inline_error_message', :locals => {:object => @user, :attribute => :description }%>
		  </div>  
		</div>

    <div class="control-group <%= has_attachment_error?(@user, "avatar") %>">
			<label class="control-label">Image*<label/>
			<div class="controls">          
			  <%= f.file_field :avatar,:class=>'span5' %>
			  <%= render :partial => 'shared/attachment_inline_error_message', :locals => {:object => @user, :attribute => :avatar }%>
			</div>
    </div>

      <div class="form-actions">
        <%= f.submit "Save Changes",:class=>"btn btn-primary"%>
        <%= link_to("Cancel", user_path(@user),:class=>'btn black-link') %>
      </div>
   </fieldset>
<% end %>

app/views/users/new.html.erb
<div class='well div-center width500'>
  <div>
  <h3>Sign up</h3>
  <%= form_for @user do |f| %>
    <%= render :partial => "form", :object => f, :locals => { :user => @user } %>
    <%= f.submit "Sign up", :class=> "btn btn-primary"  %>
  <% end %>
  </div>
</div>

app/views/users/remove_subscription.js.erb
<% if @is_removed %>
    $("#list_<%= @list.id %>.sbscr_actions").html("<%= escape_javascript subscribe_actions(@list) %> ");
<% end %>

app/views/users/reset_password.html.erb
<h1>Reset your password.</h1>

<%= render "shared/error_messages", :target => @user %>

<%= form_for @user, :url => reset_password_url do |f| %>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit "Reset Password and Log in" %>
<% end %>

app/views/users/show.html.erb
<% content_for :page_info do %>
 - User Details
<% end %>

<div>
  <% content_for :sidebar do%>
    <%= render :partial => 'urls/stacked_navigation' %>
  <% end %>

  <div class='page-header'>
    <h2> User Details </h2>
  </div>

  <%= render :partial => "users/user_details", :locals => { :user => @user } %>
</div>