config/routes.rb
ListIt::Application.routes.draw do

  resources :subscriptions

  resources :user_sessions 

  match '/auth/twitter/callback' => "user_sessions#twitter_auth"  

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
  match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation

  match 'forgot_password' => 'user_sessions#forgot_password', :as => :forgot_password, :via => :get
  match 'forgot_password' => 'user_sessions#forgot_password_lookup_email', :as => :forgot_password, :via => :post

  put 'reset_password/:reset_password_code' => 'users#reset_password_submit', :as => :reset_password, :via => :put
  get 'reset_password/:reset_password_code' => 'users#reset_password', :as => :reset_password, :via => :get  

  resources :users do
    member do
      post :add_subscription
      post :remove_subscription 
    end   
    
    resources :lists, :only => [] do
      collection do
        get :peek
      end
    end
  end

  resources :projects

  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup
  resources :lists do 
    collection do
      get "all" 
      get "search"
    end  
    member do 
      get 'up_vote'
      get 'down_vote'
    end

    resources :urls do
      collection do
        get "search"
        
      end
      member do 
      post "add_comment"
      end
    end

    resources :members  do 
      member do 
        delete "reject"
        
      end     
    end
  end
 
  
  match "members/manage" => "members#manage", :via => :get, :as => "manage_members"
  match 'fetch_url_content' => 'urls#fetch_url_content'
  match 'profile' => 'users#edit_profile'
  match 'about_us' => 'pages#about_us'
  match 'contact_us' => 'pages#contact_us'
  match 'terms_of_service' => 'pages#terms_of_service'
  match '/admin' => 'admin::users#index'
  namespace :admin do 
    match '/users' => "users#index" 
    match '/users/:id' => "users#show"
    match '/users/destroy/:id' => "users#destroy",:as => :delete_user,:via => [:delete]
    match '/users/deactivate/:id' => "users#deactivate",:as => :deactivate_user
    match '/users/activate/:id' => "users#activate",:as => :activate_user
    match '/lists/:user_id' => "lists#index",:as=>:user_list
    match '/lists/destroy/:id' => "lists#destroy",:as => :destroy_list,:via => [:delete]
  end
  

  root :to => 'user_sessions#new' 

end

app/views/shared/_attachment_inline_error_message.html.erb
<% if has_attachment_error?(object, attribute).present?  %>
  <span class='help-inline form-inline-help'>
  	<%= attachment_errors(object, attribute).join('. ') %>
  </span>
<% end %>                            

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="error_explanation" class="width250">
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
	<p class='footer-content'> 
	  Firelist &copy; Idyllic Software 2012
	  |
	  <%= link_to "Home", lists_url %>
	  |
	  <%= link_to "About Us", about_us_url %>
    <!-- |
    <%#= link_to "Contact Us", contact_us_url %>
    |
    <%#= link_to "Terms of Service", terms_of_service_url %> -->
	</p>
</footer>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "FireList", lists_url, :class => "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="<%= active_nav_class('lists') %>"><%= link_to "List", lists_path %></li>
        </ul>

        <% if current_user.present? %>
          <ul class="nav">
            <li class="<%= active_nav_class('profile') %>"><%= link_to "Profile", user_path(current_user) %></li>
          </ul>  
          <ul class="nav">
            <li class="<%= active_nav_class('notifications') %>">
              <a href='<%= manage_members_url %>'> Notifications 
                <% if notifications_exist? %>
                  <span class="badge badge-success"><%= notification_size %></span>
                <% end %>                  
              </a>
            </li>
          </ul>  
          <ul class="nav">
            <li class="<%= active_nav_class('projects')%>">
              <a href='<%= projects_url %>'>Projects</a>
            </li>
          </ul>
          <% if current_user.is_admin? %>  
            <ul class="nav">
              <li class="<%= active_nav_class('admin') %>"><%= link_to "Admin", admin_path %></li>
            </ul>        
          <% end %>
        <% end %>  

        <p class="navbar-text pull-right">
          <% if current_user %>
            Logged in as <b><%= current_user.name %></b>
            |
            <a href="<%=logout_path%>" class='white-link'>Logout</a>
          <% else %>
            <%= link_to "Sign up", signup_path, :class => 'white-link'%>
            |
            <%= link_to "Login", login_path, :class => 'white-link'%>
          <% end %>
        </p>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_inline_error_message.html.erb
<% if has_error?(object, attribute).present?  %>
  <span class='help-inline form-inline-help'>
    <%= object.errors[attribute.to_sym].join('. ') %>
  </span>
<% end %>                            

app/views/shared/_list_search.html.erb
<span> 
  <%= form_tag search_lists_url, :method => :get, :class => "well form-search" do %>
    <%= text_field_tag :search_query, nil, :placeholder => "Search Lists", :class => "input-medium search-query" %>
    <%= submit_tag "Search", :class => "btn"%>
  <% end %>  
</span>

app/views/shared/_notifications.html.erb
<% if flash[:notice].present? %>
	<div class='alert alert-success'>
		<%= flash[:notice] %>
	</div>
<% elsif flash[:error].present? %>
	<div class='alert alert-error'>
		<%= flash[:error] %>
	</div>
<% end %>

app/views/shared/_stacked_navigation_sidebar.html.erb
<% content_for :sidebar do%>
  <%= render :partial => 'urls/stacked_navigation' %>
<% end %>  

app/views/shared/_updated_info.html.erb
<span class='updated-info'>
  Updated 
  <span class='bold-text'><%= time_ago_in_words(latest_updated_time, true) %></span>
   ago
</span>

app/views/shared/_url_search.html.erb
<span> 
  <%= form_tag search_list_urls_url(@list), :method => :get, :class => "well form-search" do %>
    <%= text_field_tag :search_query, nil, :placeholder => "Search Urls", :class => "input-medium search-query" %>
    <%= submit_tag "Search", :class => "btn"%>
  <% end %>  
</span>